Repository viur-framework/viur-cli, pull requests merged in 2023-11, with the labels that each got.

#66 added sameSite to viur_2to3 script
  src/viur_cli/scripts/viur_2to3.py
Labels: feature

#65 Add documentation
  src/viur_cli/build.py
  src/viur_cli/cli.py
  src/viur_cli/conf.py
  src/viur_cli/deploy.py
  src/viur_cli/install.py
  src/viur_cli/local.py
  src/viur_cli/setup.py
  src/viur_cli/tool.py
  src/viur_cli/update.py
Labels: documentation

#76 fix: Extract scriptor zip in cwd, because it contains several subdirs
  src/viur_cli/install.py
Labels: bug, Priority: High

#75 feat: Remove duplicate index entries from `index.yaml` in `viur deploy index`
  src/viur_cli/deploy.py
Labels: feature
